---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-system-anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook:webhook-requester
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  # Anyone can pass requests to cert-manager-webhook
  # Sounds very risky! Should be fixed and/or investigated!
  name: system:anonymous