---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share-workspace
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-workspace
  template:
    metadata:
      labels:
        app: ubuntu-workspace
    spec:
      containers:
      - name: ubuntu-workspace
        image: ubuntu
        # Pointlessly idle the container
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          # name must match the volume name below
          - name: nfs-share-workspace
            mountPath: "/mnt/nfs"
            subPath: workspace
      volumes:
      - name: nfs-share-workspace
        persistentVolumeClaim:
          claimName: nfs-share-workspace
